site_name: Design Documentation
site_url: https://github.com/N-YaswanthB7/Mkdocs.git

docs_dir: docs

nav:
  # - Home: index.md
  - Get Curiosity EEPROM Card ID: Get_curiosityEepromCardID/index.md
  - Retrieving EEPROM Card Details: Getting Card Details From EEPROM/index.md

theme:
  name: material
  palette:
    - scheme: default
      primary: 'indigo'
      accent: deep orange
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: 'indigo'
      accent: deep orange
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode


markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
  - pymdownx.superfences
  - tables
